import datetime
import os
class createlog:
	#global declarations of class createlog
	#system time
	osTime = None
    #filename generated by year month and day
	filename = None
	#channellog time generated by hours and minutes
	currTime = None
	#directory for channel logs / server logs
	directory = "logs/channels/"
	#end of global declarations of class createlog

	#constructor for class createlog
	def __init__(self):
		self.osTime = datetime.datetime.now()

		self.filename = self.osTime.strftime("%Y-%m-%d")
		self.currTime = self.osTime.strftime("%H:%M")
	
		if not os.path.exists(self.directory):
			os.makedirs(self.directory)
	#end of constructor for class createlog

	#writelog helper
	def printandwriteserverlog(self, msg):
		print(msg)
		self.writeserverlog(msg)
	#end of writelog helper

	
	def writeserverlog(self, log):
		filea = open("logs/" + self.filename  + ".txt","a") 
		filea.write("[" + self.currTime + "]" + ":" + log + "\n")
		filea.close() 

	def writechannellog(self, log, channel):
			filea = open(self.directory + "/" + self.filename + ".txt","a")
			logtowrite = "[" + self.currTime + "]" + ":" + log + "\n"
			filea.write(logtowrite)
			filea.close()